name: NEXT.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or another version if you prefer

    - name: Install dependencies
      run: npm ci

    - name: Run linting (optional, remove if you don't use linting)
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build the project
      run: npm run build
